version: "3.9"
services:
  database:
    image: postgres:latest
#    restart: always
    ports:
      - 5432:5432
    container_name: chat-kt
    environment:
      - POSTGRES_USER=chatadmin
      - POSTGRES_PASSWORD=postgresthebest
      - POSTGRES_DB=chat

